// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bom-squad/protobom/pkg/sbom/ent/documenttype"
	"github.com/bom-squad/protobom/pkg/sbom/ent/predicate"
)

// DocumentTypeDelete is the builder for deleting a DocumentType entity.
type DocumentTypeDelete struct {
	config
	hooks    []Hook
	mutation *DocumentTypeMutation
}

// Where appends a list predicates to the DocumentTypeDelete builder.
func (dtd *DocumentTypeDelete) Where(ps ...predicate.DocumentType) *DocumentTypeDelete {
	dtd.mutation.Where(ps...)
	return dtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dtd *DocumentTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dtd.sqlExec, dtd.mutation, dtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dtd *DocumentTypeDelete) ExecX(ctx context.Context) int {
	n, err := dtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dtd *DocumentTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documenttype.Table, sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt))
	if ps := dtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dtd.mutation.done = true
	return affected, err
}

// DocumentTypeDeleteOne is the builder for deleting a single DocumentType entity.
type DocumentTypeDeleteOne struct {
	dtd *DocumentTypeDelete
}

// Where appends a list predicates to the DocumentTypeDelete builder.
func (dtdo *DocumentTypeDeleteOne) Where(ps ...predicate.DocumentType) *DocumentTypeDeleteOne {
	dtdo.dtd.mutation.Where(ps...)
	return dtdo
}

// Exec executes the deletion query.
func (dtdo *DocumentTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := dtdo.dtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documenttype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dtdo *DocumentTypeDeleteOne) ExecX(ctx context.Context) {
	if err := dtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
