// Code generated by ent, DO NOT EDIT.
// ------------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// ------------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------
package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bom-squad/protobom/ent/document"
	"github.com/bom-squad/protobom/ent/metadata"
	"github.com/bom-squad/protobom/ent/nodelist"
	"github.com/bom-squad/protobom/ent/predicate"
	"github.com/bom-squad/protobom/pkg/sbom"
)

// DocumentUpdate is the builder for updating Document entities.
type DocumentUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentMutation
}

// Where appends a list predicates to the DocumentUpdate builder.
func (du *DocumentUpdate) Where(ps ...predicate.Document) *DocumentUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetMetadata sets the "metadata" field.
func (du *DocumentUpdate) SetMetadata(s *sbom.Metadata) *DocumentUpdate {
	du.mutation.SetMetadata(s)
	return du
}

// SetNodeList sets the "node_list" field.
func (du *DocumentUpdate) SetNodeList(sl *sbom.NodeList) *DocumentUpdate {
	du.mutation.SetNodeList(sl)
	return du
}

// SetDocumentMetadataID sets the "document_metadata" edge to the Metadata entity by ID.
func (du *DocumentUpdate) SetDocumentMetadataID(id string) *DocumentUpdate {
	du.mutation.SetDocumentMetadataID(id)
	return du
}

// SetDocumentMetadata sets the "document_metadata" edge to the Metadata entity.
func (du *DocumentUpdate) SetDocumentMetadata(m *Metadata) *DocumentUpdate {
	return du.SetDocumentMetadataID(m.ID)
}

// SetDocumentNodeListID sets the "document_node_list" edge to the NodeList entity by ID.
func (du *DocumentUpdate) SetDocumentNodeListID(id int) *DocumentUpdate {
	du.mutation.SetDocumentNodeListID(id)
	return du
}

// SetDocumentNodeList sets the "document_node_list" edge to the NodeList entity.
func (du *DocumentUpdate) SetDocumentNodeList(n *NodeList) *DocumentUpdate {
	return du.SetDocumentNodeListID(n.ID)
}

// Mutation returns the DocumentMutation object of the builder.
func (du *DocumentUpdate) Mutation() *DocumentMutation {
	return du.mutation
}

// ClearDocumentMetadata clears the "document_metadata" edge to the Metadata entity.
func (du *DocumentUpdate) ClearDocumentMetadata() *DocumentUpdate {
	du.mutation.ClearDocumentMetadata()
	return du
}

// ClearDocumentNodeList clears the "document_node_list" edge to the NodeList entity.
func (du *DocumentUpdate) ClearDocumentNodeList() *DocumentUpdate {
	du.mutation.ClearDocumentNodeList()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DocumentUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DocumentUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DocumentUpdate) check() error {
	if _, ok := du.mutation.DocumentMetadataID(); du.mutation.DocumentMetadataCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Document.document_metadata"`)
	}
	if _, ok := du.mutation.DocumentNodeListID(); du.mutation.DocumentNodeListCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Document.document_node_list"`)
	}
	return nil
}

func (du *DocumentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Metadata(); ok {
		_spec.SetField(document.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := du.mutation.NodeList(); ok {
		_spec.SetField(document.FieldNodeList, field.TypeJSON, value)
	}
	if du.mutation.DocumentMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentMetadataTable,
			Columns: []string{document.DocumentMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.DocumentMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentMetadataTable,
			Columns: []string{document.DocumentMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.DocumentNodeListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentNodeListTable,
			Columns: []string{document.DocumentNodeListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.DocumentNodeListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentNodeListTable,
			Columns: []string{document.DocumentNodeListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DocumentUpdateOne is the builder for updating a single Document entity.
type DocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentMutation
}

// SetMetadata sets the "metadata" field.
func (duo *DocumentUpdateOne) SetMetadata(s *sbom.Metadata) *DocumentUpdateOne {
	duo.mutation.SetMetadata(s)
	return duo
}

// SetNodeList sets the "node_list" field.
func (duo *DocumentUpdateOne) SetNodeList(sl *sbom.NodeList) *DocumentUpdateOne {
	duo.mutation.SetNodeList(sl)
	return duo
}

// SetDocumentMetadataID sets the "document_metadata" edge to the Metadata entity by ID.
func (duo *DocumentUpdateOne) SetDocumentMetadataID(id string) *DocumentUpdateOne {
	duo.mutation.SetDocumentMetadataID(id)
	return duo
}

// SetDocumentMetadata sets the "document_metadata" edge to the Metadata entity.
func (duo *DocumentUpdateOne) SetDocumentMetadata(m *Metadata) *DocumentUpdateOne {
	return duo.SetDocumentMetadataID(m.ID)
}

// SetDocumentNodeListID sets the "document_node_list" edge to the NodeList entity by ID.
func (duo *DocumentUpdateOne) SetDocumentNodeListID(id int) *DocumentUpdateOne {
	duo.mutation.SetDocumentNodeListID(id)
	return duo
}

// SetDocumentNodeList sets the "document_node_list" edge to the NodeList entity.
func (duo *DocumentUpdateOne) SetDocumentNodeList(n *NodeList) *DocumentUpdateOne {
	return duo.SetDocumentNodeListID(n.ID)
}

// Mutation returns the DocumentMutation object of the builder.
func (duo *DocumentUpdateOne) Mutation() *DocumentMutation {
	return duo.mutation
}

// ClearDocumentMetadata clears the "document_metadata" edge to the Metadata entity.
func (duo *DocumentUpdateOne) ClearDocumentMetadata() *DocumentUpdateOne {
	duo.mutation.ClearDocumentMetadata()
	return duo
}

// ClearDocumentNodeList clears the "document_node_list" edge to the NodeList entity.
func (duo *DocumentUpdateOne) ClearDocumentNodeList() *DocumentUpdateOne {
	duo.mutation.ClearDocumentNodeList()
	return duo
}

// Where appends a list predicates to the DocumentUpdate builder.
func (duo *DocumentUpdateOne) Where(ps ...predicate.Document) *DocumentUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DocumentUpdateOne) Select(field string, fields ...string) *DocumentUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Document entity.
func (duo *DocumentUpdateOne) Save(ctx context.Context) (*Document, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DocumentUpdateOne) SaveX(ctx context.Context) *Document {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DocumentUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DocumentUpdateOne) check() error {
	if _, ok := duo.mutation.DocumentMetadataID(); duo.mutation.DocumentMetadataCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Document.document_metadata"`)
	}
	if _, ok := duo.mutation.DocumentNodeListID(); duo.mutation.DocumentNodeListCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Document.document_node_list"`)
	}
	return nil
}

func (duo *DocumentUpdateOne) sqlSave(ctx context.Context) (_node *Document, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Document.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, document.FieldID)
		for _, f := range fields {
			if !document.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != document.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Metadata(); ok {
		_spec.SetField(document.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := duo.mutation.NodeList(); ok {
		_spec.SetField(document.FieldNodeList, field.TypeJSON, value)
	}
	if duo.mutation.DocumentMetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentMetadataTable,
			Columns: []string{document.DocumentMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.DocumentMetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentMetadataTable,
			Columns: []string{document.DocumentMetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.DocumentNodeListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentNodeListTable,
			Columns: []string{document.DocumentNodeListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.DocumentNodeListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   document.DocumentNodeListTable,
			Columns: []string{document.DocumentNodeListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Document{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
