---
name: SLSA Source
on:
  push:
    branches:
      - "main"
    tags:
      - '**'

permissions: {}

jobs:
  # Whenever new source is pushed recompute the slsa source information.
  generate-provenance:
    permissions:
      contents: write # needed for storing the vsa in the repo.
      id-token: write # meeded to mint yokens for signing

    uses: slsa-framework/source-actions/.github/workflows/compute_slsa_source.yml@dea965cdca5e0cb422bf7b2653c9d15f678ad01c # v0.1.0
    with:
      allow-merge-commits: true
