name: build-and-test

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  go-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      stable: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}
      previous: ${{ steps.versions.outputs.GO_MINOR_VERSION_PREVIOUS }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Determine Go versions
      id: versions
      uses: carabiner-dev/actions/go/versions@2a4b2cd115ede14629b03ef7e77586d3269d4c72 # v1.2.3

  verify:
    needs: go-versions
    name: Verify generated code
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ needs.go-versions.outputs.stable }}
        check-latest: true
        cache: true

    - name: Verify proto generated code
      run: |
        hack/verify-proto.sh

    - name: Verify autogenerated fakes
      run: |
        hack/verify-fakes.sh

  test:
    needs: go-versions
    name: Go Tests (go ${{ matrix.go-version }}, ${{ matrix.os }})
    permissions:
      contents: read

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - ${{ needs.go-versions.outputs.previous }}
          - ${{ needs.go-versions.outputs.stable }}
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true

    - name: Test
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        go get -d ./...
        go test -v ./...
