# Copyright 2023 The Protobom Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Generate SBOM
        id: sbom
        uses: carabiner-dev/actions/unpack/sbom@2a4b2cd115ede14629b03ef7e77586d3269d4c72 # v1.2.3
        with:
          format: spdx
          output-path: /tmp
          codebases: "golang:." # Only generate the SBOM for the main go codebase
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@c130b4494862d330a1aa4de320076c666d0708da # v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: ${{ steps.sbom.outputs.files }}
          sbom: false
